package com.vansid.panda.app.audio

/**
 * The four sounds the game makes, and the files they come from (T-50).
 *
 * Generated by `tools/gen_sfx.py` into `art/sfx/` and packaged from there, the same
 * arrangement the sprites have: the repository holds the script, the build carries its
 * output. See §18 for why nothing here is a downloaded sample.
 */
internal enum class Sfx(
    val asset: String,
) {
    /** The cane leaving the hand. Plays on every shot, including the computer's. */
    THROW("throw.wav"),

    /** The blast. Only on a hit — a shot that sails off the map lands on nothing. */
    BOOM("boom.wav"),

    /** The match is won. */
    VICTORY("victory.wav"),

    /** The match is lost. */
    DEFEAT("defeat.wav"),
}
